# Generated by Django 6.0.1 on 2026-02-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(max_length=10)),
                ('vendido', models.BooleanField(default=False)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='SnackCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrada.entrada')),
            ],
        ),
    ]
